language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID=${{ secrets.DIFF }}
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - make test-coverage
  - make lint
notifications:
  email: false
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
