# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# Simple workflow @morphydidius

name: test-and-lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: jest test
      run: |
        make install
        make test

  lintering:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: linter test
      run: |
        make install
        make lint

  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.DIFF }}
      run: |
        make install
        make test-coverage
